version: "3.7"
services:
  postgres:
    image: debezium/postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: data_from

  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: data_to
    ports:
      - "3306:3306"

  oracle:
    image: doctorkirk/oracle-19c
    build:
      context: debezium-oracle
    environment:
      ORACLE_SID: ORCLCDB
      ORACLE_PWD: Admin123
      ORACLE_PDB: ORCLPDB1
      ORACLE_CHARACTERSET: AL32UTF8
    ports:
      - "1521:1521"
    volumes:
      - "oracle-se2-data:/opt/oracle/oradata"
      - "./db-startup-migration-scripts:/opt/oracle/scripts/startup"
      - "./db-setup-migration-scripts:/docker-entrypoint-initdb.d/setup"

  zookeeper:
    image: confluentinc/cp-zookeeper:5.5.3
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.0.1
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_SCHEMA_REGISTRY_URL: http://schema-registry:8081
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_JMX_PORT: 9991
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_CREATE_TOPICS: order-topic:3:1
    ports:
      - "9092:9092"

  debezium:
    image: debezium/connect:1.9.5.Final
    build:
      context: debezium-jdbc
    environment:
      BOOTSTRAP_SERVERS: kafka:9092
      GROUP_ID: 1
      STATUS_STORAGE_TOPIC: connect_status
      CONFIG_STORAGE_TOPIC: connect_configs
      OFFSET_STORAGE_TOPIC: connect_offsets
      CONNECT_KEY_CONVERTER: io.confluent.connect.avro.AvroConverter
      CONNECT_VALUE_CONVERTER: io.confluent.connect.avro.AvroConverter
      CONNECT_KEY_CONVERTER_SCHEMA_REGISTRY_URL: http://schema-registry:8081
      CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL: http://schema-registry:8081
    depends_on:
      - kafka
    ports:
      - "8083:8083"

  schema-registry:
    image: confluentinc/cp-schema-registry:6.2.0
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://kafka:9092
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_LISTENERS: http://schema-registry:8081
    ports:
      - "8081:8081"
    depends_on:
      - kafka
volumes:
  oracle-se2-data: { }
